/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_WAV_FILES           1
#define MMAP_WAV_CHECKSUM        0x668D

enum MMAP_WAV_LISTS {
    MMAP_WAV_OPENAI_WELCOME_WAV = 0,        /*!< openAI_welcome.wav */
};
